# Generated by Django 2.2.3 on 2019-07-22 10:03

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area_of_research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Departmennts',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.CharField(blank=True, max_length=50)),
                ('emp_pic', models.ImageField(blank=True, default='profile_image/default_img.png', upload_to='profile_image')),
                ('researcher', models.BooleanField(default=False, null=True)),
                ('coordinator', models.BooleanField(default=False, null=True)),
                ('designation', models.CharField(max_length=20, null=True)),
                ('education_short', models.CharField(max_length=500, null=True)),
                ('short_description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('area_of_interest', models.TextField(blank=True)),
                ('Chamber_Consultation_Hours', models.CharField(default='yet to announce', max_length=200)),
                ('experience_in_years', models.PositiveIntegerField(default=0)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31, null=True)),
                ('skype_link', models.URLField(blank=True)),
                ('website_link', models.URLField(blank=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='memslab.Departments')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Employee_details_topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Topic for Employee Details',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('created_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('short_description', models.TextField(default='')),
                ('project_pic', models.ImageField(blank=True, upload_to='project_image')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, 'Ongoing'), (1, 'Completed')], default=0)),
                ('budget', models.CharField(blank=True, default=None, max_length=200)),
                ('sponsoring_agency', models.CharField(default='', max_length=200)),
                ('proj_file', models.FileField(blank=True, null=True, upload_to='project_files')),
                ('people', models.ManyToManyField(to='memslab.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Project_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Project Specialization',
            },
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('year', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='project_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, upload_to='project_image')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True, default='', max_length=400, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='memslab.Project')),
            ],
            options={
                'verbose_name_plural': 'Images for Projects',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='specializaiton',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='memslab.Project_type'),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=300)),
                ('entry', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('pic', models.ImageField(blank=True, upload_to='news_images')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memslab.Employee')),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Employeedetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='memslab.Employee_details_topic')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Employee Details',
            },
        ),
    ]
