# Generated by Django 2.2.1 on 2019-06-09 07:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Departmennts',
            },
        ),
        migrations.CreateModel(
            name='Employee_details_topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(default='', max_length=500)),
            ],
            options={
                'verbose_name_plural': 'Topic for Employee Details',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=500)),
                ('description', models.CharField(default='', max_length=4000)),
                ('project_pic', models.ImageField(blank=True, upload_to='project_image')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='project_image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, upload_to='project_image', verbose_name='Image')),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(blank=True, default='', max_length=400, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete='models.DO_NOTHING', to='memslab.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Employee_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_topic', models.CharField(default='', max_length=500)),
                ('entry', models.TextField(default='')),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='memslab.Employee_details_topic')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete='models.DO_NOTHING', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Employee Details',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.CharField(default='', max_length=50)),
                ('emp_pic', models.ImageField(blank=True, default='profile_image/default_img.png', upload_to='profile_image')),
                ('researcher', models.BooleanField(default=False)),
                ('designation', models.CharField(max_length=20, null=True)),
                ('short_description', models.TextField(blank=True, default='', max_length=400, null=True)),
                ('area', models.TextField(blank=True)),
                ('Chamber_Consultation_Hours', models.CharField(default='yet to announce', max_length=200)),
                ('phone', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='memslab.Departments')),
                ('user', models.OneToOneField(null=True, on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
