# Generated by Django 2.2.3 on 2019-07-22 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='completed_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(null=True),
        ),
    ]
