# Generated by Django 2.2.3 on 2019-07-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0002_auto_20190722_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
