# Generated by Django 2.2.3 on 2019-07-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0003_auto_20190722_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='completed_at',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateField(null=True),
        ),
    ]
