# Generated by Django 2.2.1 on 2019-06-10 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0003_auto_20190610_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='project1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='first_proj', to='memslab.Project'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='project2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_proj', to='memslab.Project'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='project3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='third_proj', to='memslab.Project'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='project4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='forth_proj', to='memslab.Project'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='project5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fifth_proj', to='memslab.Project'),
        ),
    ]
