# Generated by Django 2.2.1 on 2019-06-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0004_auto_20190610_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_image',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Ongoing'), (1, 'Completed')], default=0),
        ),
    ]
