# Generated by Django 2.2.1 on 2019-06-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0005_project_image_priority'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project_image',
            name='priority',
        ),
        migrations.AddField(
            model_name='project',
            name='priority',
            field=models.IntegerField(choices=[(0, 'Ongoing'), (1, 'Completed')], default=0),
        ),
    ]
