# Generated by Django 2.2.1 on 2019-06-11 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0006_auto_20190611_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='priority',
            new_name='Status',
        ),
    ]
