# Generated by Django 2.2.1 on 2019-06-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0007_auto_20190611_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='Status',
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Ongoing'), (1, 'Completed')], default=0),
        ),
    ]
