# Generated by Django 2.2.1 on 2019-06-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0008_auto_20190611_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
