# Generated by Django 2.2.1 on 2019-06-11 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0013_auto_20190611_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
