# Generated by Django 2.2.1 on 2019-06-11 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0014_auto_20190611_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='budget',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
