# Generated by Django 2.2.1 on 2019-06-13 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memslab', '0015_auto_20190611_2056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='project1',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='project2',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='project3',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='project4',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='project5',
        ),
        migrations.AddField(
            model_name='project',
            name='Person1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='first_proj', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='Person2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='second_proj', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='Person3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='third_proj', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='Person4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='forth_proj', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='Person5',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fifth_proj', to=settings.AUTH_USER_MODEL),
        ),
    ]
