# Generated by Django 2.2.1 on 2019-06-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0016_auto_20190613_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.DO_NOTHING', to='memslab.Employee'),
        ),
    ]
