# Generated by Django 2.2.1 on 2019-06-13 17:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0017_auto_20190613_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_details',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.DO_NOTHING', to=settings.AUTH_USER_MODEL),
        ),
    ]
