# Generated by Django 2.2.1 on 2019-06-23 16:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memslab', '0018_auto_20190613_2230'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee_details',
            new_name='Employeedetails',
        ),
    ]
