# Generated by Django 2.2.2 on 2019-06-23 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0019_auto_20190623_2209'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sponsoring_agency',
            field=models.CharField(default='', max_length=200),
        ),
    ]
