# Generated by Django 2.2.2 on 2019-06-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0020_project_sponsoring_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='dep',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
