# Generated by Django 2.2.2 on 2019-06-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0021_auto_20190624_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='experience',
            field=models.CharField(default='', max_length=200),
        ),
    ]
