# Generated by Django 2.2.2 on 2019-06-24 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0022_employee_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='experience',
        ),
        migrations.AddField(
            model_name='employee',
            name='experience_in_years',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
