# Generated by Django 2.2.2 on 2019-06-24 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0024_auto_20190624_1609'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='project_image',
            options={'verbose_name_plural': 'Images for Projects'},
        ),
        migrations.AlterModelOptions(
            name='project_type',
            options={'verbose_name_plural': 'Project Specialization'},
        ),
    ]
