# Generated by Django 2.2.2 on 2019-06-24 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0025_auto_20190624_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='proj_file',
            field=models.FileField(null=True, upload_to='project_files'),
        ),
    ]
