# Generated by Django 2.2.2 on 2019-06-27 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0027_auto_20190627_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='proj_file',
            field=models.FileField(blank=True, null=True, upload_to='project_files'),
        ),
    ]
