# Generated by Django 2.2.2 on 2019-06-27 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0028_auto_20190627_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.DO_NOTHING', to='memslab.Employee'),
        ),
    ]
