# Generated by Django 2.2.2 on 2019-06-27 17:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0029_auto_20190627_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete='models.DO_NOTHING', to=settings.AUTH_USER_MODEL),
        ),
    ]
