# Generated by Django 2.2.2 on 2019-06-30 15:56

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0030_auto_20190627_2301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='entry',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
    ]
