# Generated by Django 2.2.2 on 2019-06-30 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0031_auto_20190630_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeedetails',
            name='sub_topic',
        ),
    ]
