# Generated by Django 2.2.2 on 2019-06-30 16:51

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0032_remove_employeedetails_sub_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='entry',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
    ]
