# Generated by Django 2.2.2 on 2019-07-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0033_auto_20190630_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='skype_link',
            field=models.URLField(blank=True),
        ),
    ]
