# Generated by Django 2.2.2 on 2019-07-02 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0034_employee_skype_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='website_link',
            field=models.URLField(blank=True),
        ),
    ]
