# Generated by Django 2.2.2 on 2019-07-03 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0036_auto_20190702_2213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
