# Generated by Django 2.2.2 on 2019-07-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0037_remove_project_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Ongoing'), (1, 'Completed')], default=0),
        ),
    ]
