# Generated by Django 2.2.2 on 2019-07-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0038_project_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='Person4',
            new_name='Person_4',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Person5',
            new_name='Person_5',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Person1',
            new_name='person_1',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Person2',
            new_name='person_2',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='Person3',
            new_name='person_3',
        ),
        migrations.AlterField(
            model_name='project',
            name='sponsoring_agency',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
