# Generated by Django 2.2.2 on 2019-07-03 20:48

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0041_auto_20190704_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='short_description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
    ]
