# Generated by Django 2.2.2 on 2019-07-04 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0042_auto_20190704_0218'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='people',
            field=models.ManyToManyField(to='memslab.Employee'),
        ),
    ]
