# Generated by Django 2.2.2 on 2019-07-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0044_auto_20190704_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='education',
            field=models.TextField(blank=True),
        ),
    ]
