# Generated by Django 2.2.2 on 2019-07-04 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0045_employee_education'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='education',
        ),
        migrations.AddField(
            model_name='employee',
            name='education_short',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
