# Generated by Django 2.2.3 on 2019-07-06 21:31

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0046_auto_20190704_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='coordinator',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='researcher',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=300)),
                ('entry', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
                ('date', models.DateField(blank=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete='models.CASCADE', to='memslab.Employee')),
            ],
            options={
                'verbose_name_plural': 'News',
            },
        ),
    ]
