# Generated by Django 2.2.3 on 2019-07-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0047_auto_20190707_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='date',
        ),
        migrations.AddField(
            model_name='news',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
