# Generated by Django 2.2.3 on 2019-07-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0048_auto_20190707_0304'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='pic',
            field=models.ImageField(blank=True, upload_to='project_image'),
        ),
        migrations.AddField(
            model_name='news',
            name='summary',
            field=models.TextField(blank=True),
        ),
    ]
