# Generated by Django 2.2.3 on 2019-07-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0050_auto_20190710_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_pic',
            field=models.ImageField(blank=True, default='project_image/default_image.png', upload_to='project_image'),
        ),
    ]
