# Generated by Django 2.2.3 on 2019-07-10 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0052_auto_20190711_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pic',
            field=models.ImageField(blank=True, default='news_images/default-image.jpg', upload_to='news_images'),
        ),
    ]
