# Generated by Django 2.2.3 on 2019-07-16 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0053_auto_20190711_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='summary',
        ),
    ]
