# Generated by Django 2.2.3 on 2019-07-18 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0056_remove_project_image_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='project_image',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
