# Generated by Django 2.2.3 on 2019-07-21 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0058_project_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
