# Generated by Django 2.2.3 on 2019-07-21 15:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0060_project_completed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Area_of_research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default='')),
            ],
        ),
    ]
