# Generated by Django 2.2.3 on 2019-07-21 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0061_area_of_research_publications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='area_of_research',
            old_name='points',
            new_name='entry',
        ),
        migrations.RenameField(
            model_name='publications',
            old_name='points',
            new_name='entry',
        ),
    ]
