# Generated by Django 2.2.3 on 2019-07-21 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memslab', '0062_auto_20190721_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='publications',
            name='year',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
